"""ajustando questions e answers

Revision ID: 012fd298b577
Revises: 
Create Date: 2025-06-14 16:06:47.824152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '012fd298b577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collected_data_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('answer_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'collected_data', ['collected_data_id'], ['collected_data_id'])
        batch_op.drop_column('performed_task_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_success_criterion_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('question_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'key_success_criterion', ['key_success_criterion_id'], ['key_success_criterion_id'])
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('question_ibfk_1', 'task', ['task_id'], ['task_id'])
        batch_op.drop_column('key_success_criterion_id')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('performed_task_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('answer_ibfk_1', 'performed_task', ['performed_task_id'], ['performed_task_id'])
        batch_op.drop_column('collected_data_id')

    # ### end Alembic commands ###
