"""widen navigation title and url columns

Revision ID: 1141a64c9458
Revises: 4ef2e61f029a
Create Date: 2026-08-14 12:13:56.979209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1141a64c9458'
down_revision = '4ef2e61f029a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('navigation', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=2048),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('navigation', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
