"""creating navigation table and updating developer_questionnaire

Revision ID: 1ce06535edbc
Revises: 
Create Date: 2025-03-31 09:22:46.280761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ce06535edbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previus_xp', sa.Enum('NEVER', 'RARELY', 'OFTEN', 'AWAYS', name='previousexperience'), nullable=False))
        batch_op.add_column(sa.Column('segment', sa.Enum('ACADEMIA', 'INDUSTRY', 'BOTH', name='segmenttype'), nullable=False))
        batch_op.alter_column('academic_level',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'DOCTORATE', name='academiclevel'),
               existing_nullable=False)
        batch_op.alter_column('comments',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('seco')
        batch_op.drop_column('experience')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('experience', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seco', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('comments',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('academic_level',
               existing_type=sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'DOCTORATE', name='academiclevel'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('segment')
        batch_op.drop_column('previus_xp')

    # ### end Alembic commands ###
