"""Remove unique constraint from Navigation.collected_data_id

Revision ID: 205f4325f8d8
Revises: 2d28bb356911
Create Date: 2025-04-11 17:55:37.579456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205f4325f8d8'
down_revision = '2d28bb356911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('navigation', schema=None) as batch_op:
        batch_op.drop_index('collected_data_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('navigation', schema=None) as batch_op:
        batch_op.create_index('collected_data_id', ['collected_data_id'], unique=True)

    # ### end Alembic commands ###
