"""updating database

Revision ID: 2d28bb356911
Revises: 643a578d3f39
Create Date: 2025-04-11 10:17:29.163517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d28bb356911'
down_revision = '643a578d3f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('developer_questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=False))
        batch_op.drop_constraint('developer_questionnaire_ibfk_1', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('performed_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'task', ['task_id'], ['task_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performed_task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('task_id')

    with op.batch_alter_table('developer_questionnaire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('developer_questionnaire_ibfk_1', 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('experience')

    # ### end Alembic commands ###
