"""baseline: all existing tables

Revision ID: 4ef2e61f029a
Revises: 
Create Date: 2026-05-05 15:52:35.096956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef2e61f029a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conditioning_factor_transp',
    sa.Column('conditioning_factor_transp_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('conditioning_factor_transp_id')
    )
    op.create_table('dx_factor',
    sa.Column('dx_factor_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('dx_factor_id')
    )
    op.create_table('guideline',
    sa.Column('guidelineID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('guidelineID')
    )
    op.create_table('seco_dimension',
    sa.Column('seco_dimension_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('seco_dimension_id')
    )
    op.create_table('seco_process',
    sa.Column('seco_process_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('seco_process_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('passw', sa.LargeBinary(length=60), nullable=False),
    sa.Column('type', sa.Enum('ADMIN', 'SECO_MANAGER', 'USER', name='usertype'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('evaluation',
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('seco_portal', sa.String(length=100), nullable=False),
    sa.Column('seco_portal_url', sa.String(length=500), nullable=False),
    sa.Column('seco_type', sa.Enum('OPEN_SOURCE', 'HYBRID', 'PROPRIETARY', name='seco_type_enum'), nullable=False),
    sa.Column('manager_objective', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id'),
    sa.UniqueConstraint('name', 'seco_portal', 'seco_portal_url', 'user_id', name='uq_evaluation_details')
    )
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_seco_type'), ['seco_type'], unique=False)

    op.create_table('guideline_conditioning_factor',
    sa.Column('guideline_id', sa.Integer(), nullable=True),
    sa.Column('conditioning_factor_transp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conditioning_factor_transp_id'], ['conditioning_factor_transp.conditioning_factor_transp_id'], ),
    sa.ForeignKeyConstraint(['guideline_id'], ['guideline.guidelineID'], )
    )
    op.create_table('guideline_dx_factor',
    sa.Column('guideline_id', sa.Integer(), nullable=True),
    sa.Column('dx_factor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dx_factor_id'], ['dx_factor.dx_factor_id'], ),
    sa.ForeignKeyConstraint(['guideline_id'], ['guideline.guidelineID'], )
    )
    op.create_table('guideline_seco_dimension',
    sa.Column('guideline_id', sa.Integer(), nullable=True),
    sa.Column('seco_dimension_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guideline_id'], ['guideline.guidelineID'], ),
    sa.ForeignKeyConstraint(['seco_dimension_id'], ['seco_dimension.seco_dimension_id'], )
    )
    op.create_table('guideline_seco_process',
    sa.Column('guideline_id', sa.Integer(), nullable=True),
    sa.Column('seco_process_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guideline_id'], ['guideline.guidelineID'], ),
    sa.ForeignKeyConstraint(['seco_process_id'], ['seco_process.seco_process_id'], )
    )
    op.create_table('key_success_criterion',
    sa.Column('key_success_criterion_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('guideline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guideline_id'], ['guideline.guidelineID'], ),
    sa.PrimaryKeyConstraint('key_success_criterion_id')
    )
    op.create_table('process_task',
    sa.Column('seco_process_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seco_process_id'], ['seco_process.seco_process_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], )
    )
    op.create_table('task_seco_type',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('seco_type', sa.Enum('OPEN_SOURCE', 'HYBRID', 'PROPRIETARY', name='task_seco_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('task_id', 'seco_type'),
    sa.UniqueConstraint('task_id', 'seco_type', name='uq_task_seco_type')
    )
    with op.batch_alter_table('task_seco_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_seco_type_seco_type'), ['seco_type'], unique=False)

    op.create_table('collected_data',
    sa.Column('collected_data_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('cod', sa.String(length=100), nullable=False),
    sa.Column('sessionId', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.evaluation_id'], ),
    sa.PrimaryKeyConstraint('collected_data_id')
    )
    op.create_table('evaluation_SECO_process',
    sa.Column('evaluation_id', sa.BigInteger(), nullable=True),
    sa.Column('seco_process_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.evaluation_id'], ),
    sa.ForeignKeyConstraint(['seco_process_id'], ['seco_process.seco_process_id'], )
    )
    op.create_table('evaluation_ksc_weight',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('ksc_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.evaluation_id'], ),
    sa.ForeignKeyConstraint(['ksc_id'], ['key_success_criterion.key_success_criterion_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('example',
    sa.Column('example_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('key_success_criterion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_success_criterion_id'], ['key_success_criterion.key_success_criterion_id'], ),
    sa.PrimaryKeyConstraint('example_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('key_success_criterion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['key_success_criterion_id'], ['key_success_criterion.key_success_criterion_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('answer',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Integer(), nullable=False),
    sa.Column('collected_data_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collected_data_id'], ['collected_data.collected_data_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('developer_questionnaire',
    sa.Column('developer_questionnaire_id', sa.Integer(), nullable=False),
    sa.Column('academic_level', sa.Enum('HIGH_SCHOOL', 'BACHELOR', 'MASTER', 'DOCTORATE', name='academiclevel'), nullable=False),
    sa.Column('previus_xp', sa.Enum('NEVER', 'RARELY', 'OFTEN', 'AWAYS', name='previousexperience'), nullable=False),
    sa.Column('emotion', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=500), nullable=False),
    sa.Column('segment', sa.Enum('ACADEMIA', 'INDUSTRY', 'BOTH', name='segmenttype'), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('collected_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collected_data_id'], ['collected_data.collected_data_id'], ),
    sa.PrimaryKeyConstraint('developer_questionnaire_id'),
    sa.UniqueConstraint('collected_data_id')
    )
    op.create_table('navigation',
    sa.Column('navigation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Enum('PAGE_NAVIGATION', 'TAB_SWITCH', name='navigationtype'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('collected_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collected_data_id'], ['collected_data.collected_data_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('navigation_id')
    )
    op.create_table('performed_task',
    sa.Column('performed_task_id', sa.Integer(), nullable=False),
    sa.Column('initial_timestamp', sa.DateTime(), nullable=False),
    sa.Column('final_timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SOLVED', 'COULDNT_SOLVE', 'NOT_SURE', name='performedtaskstatus'), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('collected_data_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collected_data_id'], ['collected_data.collected_data_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('performed_task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performed_task')
    op.drop_table('navigation')
    op.drop_table('developer_questionnaire')
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('example')
    op.drop_table('evaluation_ksc_weight')
    op.drop_table('evaluation_SECO_process')
    op.drop_table('collected_data')
    with op.batch_alter_table('task_seco_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_seco_type_seco_type'))

    op.drop_table('task_seco_type')
    op.drop_table('process_task')
    op.drop_table('key_success_criterion')
    op.drop_table('guideline_seco_process')
    op.drop_table('guideline_seco_dimension')
    op.drop_table('guideline_dx_factor')
    op.drop_table('guideline_conditioning_factor')
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_seco_type'))
        batch_op.drop_index(batch_op.f('ix_evaluation_created_at'))

    op.drop_table('evaluation')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('seco_process')
    op.drop_table('seco_dimension')
    op.drop_table('guideline')
    op.drop_table('dx_factor')
    op.drop_table('conditioning_factor_transp')
    # ### end Alembic commands ###
