"""removing seco_portal column from collectedData

Revision ID: 643a578d3f39
Revises: fbd044092353
Create Date: 2025-04-05 16:24:16.791072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '643a578d3f39'
down_revision = 'fbd044092353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_data', schema=None) as batch_op:
        batch_op.drop_column('seco_portal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collected_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seco_portal', mysql.VARCHAR(length=500), nullable=False))

    # ### end Alembic commands ###
