"""add responsible and deadline to ai_action

Revision ID: a3c9d5e7f210
Revises: e01d1ef461c0
Create Date: 2026-10-05 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c9d5e7f210'
down_revision = 'e01d1ef461c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_action', schema=None) as batch_op:
        batch_op.drop_column('deadline')
        batch_op.drop_column('responsible')

    # ### end Alembic commands ###
