"""Add heatmap_points table

Revision ID: add_heatmap_points
Revises: c1e1d708ec8c
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_heatmap_points'
down_revision = 'c1e1d708ec8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heatmap_points',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('collected_data_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('point_type', sa.String(length=20), nullable=False),
    sa.Column('scroll_position', sa.Integer(), nullable=False),
    sa.Column('page_width', sa.Integer(), nullable=False),
    sa.Column('page_height', sa.Integer(), nullable=False),
    sa.Column('page_title', sa.String(length=200), nullable=True),
    sa.Column('page_description', sa.Text(), nullable=True),
    sa.Column('element_id', sa.String(length=100), nullable=True),
    sa.Column('element_class', sa.String(length=200), nullable=True),
    sa.Column('element_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collected_data_id'], ['collected_data.collected_data_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('point_id')
    )
    op.create_index('idx_heatmap_collected_data_id', 'heatmap_points', ['collected_data_id'], unique=False)
    op.create_index('idx_heatmap_task_id', 'heatmap_points', ['task_id'], unique=False)
    op.create_index('idx_heatmap_timestamp', 'heatmap_points', ['timestamp'], unique=False)
    op.create_index('idx_heatmap_url', 'heatmap_points', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_heatmap_url', table_name='heatmap_points')
    op.drop_index('idx_heatmap_timestamp', table_name='heatmap_points')
    op.drop_index('idx_heatmap_task_id', table_name='heatmap_points')
    op.drop_index('idx_heatmap_collected_data_id', table_name='heatmap_points')
    op.drop_table('heatmap_points')
    # ### end Alembic commands ###



