"""adiciona descricao do portal

Revision ID: b6f8b8ba394e
Revises: e01d1ef461c0
Create Date: 2026-09-10 01:57:43.336387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f8b8ba394e'
down_revision = 'e01d1ef461c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seco_portal_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_column('seco_portal_description')

    # ### end Alembic commands ###
