"""adiciona tabela doubt (RF-03)

Revision ID: e01d1ef461c0
Revises: f7e2543367c7
Create Date: 2026-09-04 17:24:18.867371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01d1ef461c0'
down_revision = 'f7e2543367c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubt',
    sa.Column('doubt_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('elapsed_time', sa.String(length=10), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('seco_process_id', sa.Integer(), nullable=True),
    sa.Column('collected_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collected_data_id'], ['collected_data.collected_data_id'], ),
    sa.ForeignKeyConstraint(['seco_process_id'], ['seco_process.seco_process_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ),
    sa.PrimaryKeyConstraint('doubt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doubt')
    # ### end Alembic commands ###
