"""add manual_rank to ai_action

Revision ID: f7e2543367c7
Revises: b7d2e4a91c36
Create Date: 2026-08-21 20:27:39.568765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e2543367c7'
down_revision = 'b7d2e4a91c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_rank', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_action', schema=None) as batch_op:
        batch_op.drop_column('manual_rank')

    # ### end Alembic commands ###
