"""Adding seco_portal_url

Revision ID: fbd044092353
Revises: 1ce06535edbc
Create Date: 2025-03-31 09:58:12.266057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd044092353'
down_revision = '1ce06535edbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seco_portal_url', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_column('seco_portal_url')

    # ### end Alembic commands ###
